on: push
name: Build and test
jobs:
  unit_tests:
    name: Unit tests
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ["7.2", "7.3", "7.4"]
        composer-update: ["", "--prefer-stable --prefer-lowest"]
      fail-fast: false
    steps:
      - uses: actions/checkout@master
      - name: Installing PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-version }}
          # These extensions are required by PHP 7.4
          extension-csv: mbstring, xmlwriter
      - name: Composer update
        run: composer update ${{ matrix.composer-update }}
      - name: Unit tests
        run: phpdbg -qrr vendor/bin/phpunit
      - name: Unit Codecov
        if: matrix.php-version == '7.3' && !matrix.composer-update
        uses: Atrox/codecov-action@v0.1.3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  specification_lint:
    name: Specification linting
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Lint specification
        uses: docker://wework/speccy
        with:
          args: lint spec/openapi-1.0.0.yml
